// Grammar Vault - Levels Data
// Loaded via <script src="levels.js"> so it works when opening grammar_vault.html
// directly (file://) with no local server — same reasoning as questions.js.
//
// LEVEL_TEMPLATES: one entry per level. Each has:
//   name   - level title shown in the HUD and banners
//   bg/t1/t2/wall/exit - color theme (hex strings)
//   npcs   - array of {gx, gy, color, name, category}
//            gx/gy are grid coordinates (grid is 26 wide x 15 tall, 0-indexed).
//            category must match a CATEGORY: in questions.js.
//
// WALLS: shared obstacle layout used by every level (grid coordinates).
// Player always starts at grid (11,6); the EXIT is always near the top-right.
//
// NPC count increases level by level: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23.

const LEVEL_TEMPLATES = [
  { name:'Grammar Village',    skin:'village', bg:'#eaf7d9',t1:'#cdeaa0',t2:'#bfe291',wall:'#5fa64a',exit:'#FFD23F',
    npcs:[
      {gx:3, gy:3, color:'#ff8866',name:'Granny Agatha',   category:'Grammar'},
      {gx:16,gy:7, color:'#66aaff',name:'Captain Vex',      category:'Grammar'},
      {gx:12,gy:2, color:'#99ff99',name:'Tense Tom',        category:'Grammar'},
      {gx:8, gy:10,color:'#cc88ff',name:'Prof. Plum',       category:'Vocabulary'},
    ]},

  { name:'Punctuation Plains', skin:'plains', bg:'#eaf3fb',t1:'#cfe6f7',t2:'#bfdcf2',wall:'#5b7bb8',exit:'#3EC6E0',
    npcs:[
      {gx:2, gy:9, color:'#ffcc44',name:'Comma Carl',       category:'Punctuation'},
      {gx:12,gy:4, color:'#44ccb8',name:'Apostrophe Annie', category:'Punctuation'},
      {gx:18,gy:9, color:'#ff6699',name:'Question Quinn',   category:'Punctuation'},
      {gx:7, gy:5, color:'#5b9bd5',name:'Colon Colin',      category:'Punctuation'},
      {gx:15,gy:2, color:'#ff9f66',name:'Semicolon Sal',    category:'Punctuation'},
    ]},

  { name:'Spelling Summit',    skin:'summit', bg:'#f3ece0',t1:'#e6d3ae',t2:'#dcc596',wall:'#8a6a45',exit:'#FF6FB5',
    npcs:[
      {gx:3, gy:3, color:'#ffaa44',name:'Spelling Bee Sam', category:'Spelling'},
      {gx:16,gy:8, color:'#44b8d8',name:'Silent Sue',       category:'Spelling'},
      {gx:8, gy:9, color:'#a877dd',name:'Dave Double-L',    category:'Spelling'},
      {gx:2, gy:12,color:'#ff66cc',name:'Mia Mnemonic',     category:'Spelling'},
      {gx:4, gy:8, color:'#ff8888',name:'Hank Homophones',  category:'Reading Comprehension'},
      {gx:19,gy:2, color:'#8fc93a',name:'Wanda Wordsmith',  category:'Vocabulary'},
    ]},

  { name:'Vocabulary Valley',  skin:'valley', bg:'#f3ecfb',t1:'#e2cdf5',t2:'#d6bced',wall:'#8a5fc9',exit:'#FF9F45',
    npcs:[
      {gx:8, gy:5, color:'#aa66ff',name:'Lexi Lexicon',     category:'Vocabulary'},
      {gx:23,gy:12,color:'#cc99ff',name:'Sy Nonym',         category:'Vocabulary'},
      {gx:19,gy:2, color:'#9955dd',name:'Anton Antonym',    category:'Vocabulary'},
      {gx:2, gy:12,color:'#77bbff',name:'Gus the Grammarian',category:'Grammar'},
      {gx:14,gy:12,color:'#ff9ecf',name:"Pip the Punctuator",category:'Punctuation'},
      {gx:2, gy:2, color:'#ffcc44',name:"Ollie O'Speller",  category:'Spelling'},
      {gx:8, gy:11,color:'#ff9999',name:'Rhea Reads',       category:'Reading Comprehension'},
    ]},

  { name:'The Final Archive',  skin:'archive', bg:'#f7ece1',t1:'#e8cba6',t2:'#dcb98f',wall:'#a56a3a',exit:'#FFD23F',
    npcs:[
      {gx:18,gy:10,color:'#e2574c',name:'Archivist Thane',  category:'Reading Comprehension'},
      {gx:2, gy:2, color:'#e88a80',name:'Sage Elenora',     category:'Reading Comprehension'},
      {gx:7, gy:12,color:'#c9453d',name:'Keeper Rook',      category:'Reading Comprehension'},
      {gx:12,gy:2, color:'#5b8fd8',name:'Elder Marcus',     category:'Grammar'},
      {gx:22,gy:2, color:'#7fb0e8',name:'Scribe Nadia',     category:'Grammar'},
      {gx:2, gy:8, color:'#44ccb8',name:'Inkwell Ivan',     category:'Punctuation'},
      {gx:12,gy:8, color:'#e8a23e',name:'Old Ortho',        category:'Spelling'},
      {gx:7, gy:5, color:'#b87fe0',name:'Sybil Synonym',    category:'Vocabulary'},
    ]},
  { name:'Adjective Archipelago',    skin:'archipelago', bg:'#eafaf5',t1:'#cdeee0',t2:'#bce4d2',wall:'#3ea88a',exit:'#3EC6E0',
    npcs:[
      {gx:10, gy:4, color:'#88ccaa',name:'Fenwick Articleton',   category:'Grammar'},
      {gx:5, gy:13, color:'#ff8888',name:'Sylvie Mnemonic',   category:'Spelling'},
      {gx:22, gy:5, color:'#66aaff',name:'Gus Subjectine',   category:'Grammar'},
      {gx:15, gy:6, color:'#88ccaa',name:'Vera Clausewell',   category:'Grammar'},
      {gx:7, gy:13, color:'#ff6699',name:'Carl Colonade',   category:'Punctuation'},
      {gx:5, gy:11, color:'#99ff99',name:'Petra Predicate',   category:'Grammar'},
      {gx:3, gy:5, color:'#5599ee',name:'Cyrus Clausewell',   category:'Grammar'},
      {gx:19, gy:10, color:'#ff4444',name:'Cole Contextine',   category:'Reading Comprehension'},
      {gx:22, gy:8, color:'#cc88ff',name:'Rhyma Wordsmith',   category:'Vocabulary'},
    ]},

  { name:'Comma Canyon',    skin:'canyon', bg:'#fdf0e4',t1:'#f0d2ae',t2:'#e5be92',wall:'#c26a3e',exit:'#FF9F45',
    npcs:[
      {gx:2, gy:10, color:'#88ddff',name:'Colin Commington',   category:'Punctuation'},
      {gx:4, gy:11, color:'#88ddff',name:'Perry Exclama',   category:'Punctuation'},
      {gx:6, gy:9, color:'#dd6666',name:'Contexta Chapterly',   category:'Reading Comprehension'},
      {gx:19, gy:13, color:'#ddaa55',name:'Sylvie Silentson',   category:'Spelling'},
      {gx:14, gy:11, color:'#aa66ff',name:'Thesa Thesauris',   category:'Vocabulary'},
      {gx:19, gy:4, color:'#ffcc44',name:'Sal Quotewright',   category:'Punctuation'},
      {gx:4, gy:10, color:'#99ff99',name:'Roland Verbington',   category:'Grammar'},
      {gx:2, gy:3, color:'#ffcc44',name:'Annie Commington',   category:'Punctuation'},
      {gx:1, gy:6, color:'#99ff99',name:'Petra Adjectivo',   category:'Grammar'},
      {gx:11, gy:5, color:'#44ffcc',name:'Brack Ellipsius',   category:'Punctuation'},
    ]},

  { name:'Silent Letter Swamp',    skin:'swamp', bg:'#eaf7ee',t1:'#c8e8cf',t2:'#b6dfc0',wall:'#4a8a63',exit:'#4CD964',
    npcs:[
      {gx:11, gy:4, color:'#bb88ff',name:'Mia Syllabicus',   category:'Spelling'},
      {gx:1, gy:6, color:'#cc3333',name:'Thane Analytika',   category:'Reading Comprehension'},
      {gx:13, gy:11, color:'#ff66cc',name:'Benny Wordwright',   category:'Spelling'},
      {gx:15, gy:6, color:'#ffaa44',name:'Sue Homophones',   category:'Spelling'},
      {gx:2, gy:5, color:'#5599ee',name:'Vera Predicate',   category:'Grammar'},
      {gx:11, gy:3, color:'#bb88ff',name:'Consie Alphabette',   category:'Spelling'},
      {gx:10, gy:4, color:'#cc99ff',name:'Suffix Meaningford',   category:'Vocabulary'},
      {gx:19, gy:8, color:'#44ccff',name:'Dave Spellman',   category:'Spelling'},
      {gx:6, gy:3, color:'#bb88ff',name:'Sylvie Mnemonic',   category:'Spelling'},
      {gx:3, gy:5, color:'#ffaa88',name:'Quill Semicolonia',   category:'Punctuation'},
      {gx:8, gy:3, color:'#88ccaa',name:'Marla Pronounce',   category:'Grammar'},
    ]},

  { name:'Metaphor Meadows',    skin:'meadow', bg:'#fdf0f7',t1:'#f7d9ec',t2:'#f0c8e2',wall:'#c96fae',exit:'#FF6FB5',
    npcs:[
      {gx:12, gy:6, color:'#cc99ff',name:'Thesa Antonym',   category:'Vocabulary'},
      {gx:19, gy:7, color:'#ffcc44',name:'Semi Commington',   category:'Punctuation'},
      {gx:13, gy:2, color:'#88ddff',name:'Sal Dashford',   category:'Punctuation'},
      {gx:20, gy:12, color:'#aa66ff',name:'Wanda Lexicon',   category:'Vocabulary'},
      {gx:24, gy:5, color:'#9955dd',name:'Anton Definitia',   category:'Vocabulary'},
      {gx:14, gy:13, color:'#cc99ff',name:'Prefixia Vocabelle',   category:'Vocabulary'},
      {gx:9, gy:10, color:'#ff7777',name:'Elenora Inferson',   category:'Reading Comprehension'},
      {gx:4, gy:11, color:'#9955dd',name:'Zin Meaningford',   category:'Vocabulary'},
      {gx:7, gy:5, color:'#5599ee',name:'Fenwick Articleton',   category:'Grammar'},
      {gx:11, gy:13, color:'#99ff99',name:'Cyrus Predicate',   category:'Grammar'},
      {gx:23, gy:10, color:'#ffaa44',name:'Consie Double-L',   category:'Spelling'},
      {gx:4, gy:13, color:'#bb77ee',name:'Metta Thesauris',   category:'Vocabulary'},
    ]},

  { name:'Story Structure Straits',    skin:'straits', bg:'#eaf6fb',t1:'#c9e8f5',t2:'#b3dcf0',wall:'#3a7ea8',exit:'#3EC6E0',
    npcs:[
      {gx:5, gy:1, color:'#88ccaa',name:'Odette Grammarian',   category:'Grammar'},
      {gx:22, gy:8, color:'#ff9999',name:'Narro Themeston',   category:'Reading Comprehension'},
      {gx:18, gy:6, color:'#dd6666',name:'Chronicle Reads',   category:'Reading Comprehension'},
      {gx:3, gy:6, color:'#aa66ff',name:'Sy Wordsmith',   category:'Vocabulary'},
      {gx:7, gy:7, color:'#ee8888',name:'Cole Themeston',   category:'Reading Comprehension'},
      {gx:17, gy:2, color:'#ee8888',name:'Inferra Themeston',   category:'Reading Comprehension'},
      {gx:17, gy:10, color:'#88ddff',name:'Semi Parenthesi',   category:'Punctuation'},
      {gx:5, gy:8, color:'#88ccaa',name:'Petra Adjectivo',   category:'Grammar'},
      {gx:23, gy:7, color:'#dd6666',name:'Elenora Passagewick',   category:'Reading Comprehension'},
      {gx:5, gy:2, color:'#ffaa88',name:'Carl Hyphenwell',   category:'Punctuation'},
      {gx:20, gy:9, color:'#ffaa44',name:'Sue Syllabicus',   category:'Spelling'},
      {gx:2, gy:10, color:'#ff4444',name:'Rhea Detailson',   category:'Reading Comprehension'},
      {gx:24, gy:9, color:'#ee8888',name:'Plotwell Analytika',   category:'Reading Comprehension'},
    ]},

  { name:'Tense Temple',    skin:'temple', bg:'#fbf3e2',t1:'#eeddb3',t2:'#e4cf99',wall:'#b8923f',exit:'#FFD23F',
    npcs:[
      {gx:16, gy:8, color:'#5599ee',name:'Ines Grammarian',   category:'Grammar'},
      {gx:20, gy:3, color:'#cc99ff',name:'Sy Definitia',   category:'Vocabulary'},
      {gx:12, gy:12, color:'#ff66cc',name:'Sue Syllabicus',   category:'Spelling'},
      {gx:10, gy:10, color:'#ff9999',name:'Cole Plotford',   category:'Reading Comprehension'},
      {gx:21, gy:9, color:'#ffaa88',name:'Perry Bracketine',   category:'Punctuation'},
      {gx:10, gy:11, color:'#77bbff',name:'Petra Pronounce',   category:'Grammar'},
      {gx:11, gy:5, color:'#ff66cc',name:'Rooter Rooter',   category:'Spelling'},
      {gx:19, gy:3, color:'#77bbff',name:'Corvin Grammarian',   category:'Grammar'},
      {gx:11, gy:9, color:'#5599ee',name:'Gus Pronounce',   category:'Grammar'},
      {gx:15, gy:13, color:'#9955dd',name:'Thesa Vocabelle',   category:'Vocabulary'},
      {gx:11, gy:3, color:'#88ccaa',name:'Tobias Pronounce',   category:'Grammar'},
      {gx:7, gy:10, color:'#4488dd',name:'Nadia Modifi',   category:'Grammar'},
      {gx:7, gy:9, color:'#77bbff',name:'Vera Grammarian',   category:'Grammar'},
      {gx:24, gy:8, color:'#ffcc44',name:'Colin Apostrophe',   category:'Punctuation'},
    ]},

  { name:'Quotation Quarry',    skin:'quarry', bg:'#eef1f7',t1:'#d4dae6',t2:'#c4ccdc',wall:'#5b6a8a',exit:'#7C5CFF',
    npcs:[
      {gx:1, gy:12, color:'#44ffcc',name:'Ellie Colonade',   category:'Punctuation'},
      {gx:23, gy:6, color:'#88ddff',name:'Brack Commington',   category:'Punctuation'},
      {gx:3, gy:2, color:'#ffdd77',name:'Hy Parenthesi',   category:'Punctuation'},
      {gx:9, gy:12, color:'#ff6699',name:'Quill Ellipsius',   category:'Punctuation'},
      {gx:11, gy:12, color:'#ffdd77',name:'Annie Exclama',   category:'Punctuation'},
      {gx:13, gy:12, color:'#aa66ff',name:'Zin Idiomatic',   category:'Vocabulary'},
      {gx:17, gy:6, color:'#4488dd',name:'Vera Clausewell',   category:'Grammar'},
      {gx:24, gy:10, color:'#ff8888',name:'Sue Wordwright',   category:'Spelling'},
      {gx:8, gy:12, color:'#ff6699',name:'Ollie Quotewright',   category:'Punctuation'},
      {gx:19, gy:8, color:'#66aaff',name:'Dahlia Articleton',   category:'Grammar'},
      {gx:11, gy:11, color:'#ff4444',name:'Inferra Passagewick',   category:'Reading Comprehension'},
      {gx:5, gy:9, color:'#9955dd',name:'Lexi Meaningford',   category:'Vocabulary'},
      {gx:20, gy:6, color:'#88ddff',name:'Colin Periodson',   category:'Punctuation'},
      {gx:19, gy:5, color:'#ff6699',name:'Quinn Ellipsius',   category:'Punctuation'},
      {gx:7, gy:7, color:'#ff66cc',name:'Sylvie Mnemonic',   category:'Spelling'},
    ]},

  { name:'Homophone Hollow',    skin:'hollow', bg:'#f3eefb',t1:'#ddd0ee',t2:'#cfc0e5',wall:'#7a5ca3',exit:'#7C5CFF',
    npcs:[
      {gx:13, gy:2, color:'#ffcc88',name:'Prefixia Etymon',   category:'Vocabulary'},
      {gx:15, gy:10, color:'#ffaa44',name:'Alva Rooter',   category:'Spelling'},
      {gx:19, gy:2, color:'#ddaa55',name:'Vowella Homophones',   category:'Spelling'},
      {gx:11, gy:2, color:'#ff8888',name:'Dave Homophones',   category:'Spelling'},
      {gx:15, gy:6, color:'#bb88ff',name:'Dot Spellman',   category:'Spelling'},
      {gx:7, gy:13, color:'#ff9999',name:'Rhea Contextine',   category:'Reading Comprehension'},
      {gx:13, gy:12, color:'#4488dd',name:'Nadia Syntaxia',   category:'Grammar'},
      {gx:24, gy:8, color:'#ffaa44',name:'Silas Alphabette',   category:'Spelling'},
      {gx:10, gy:11, color:'#ff8888',name:'Mia Spellman',   category:'Spelling'},
      {gx:20, gy:6, color:'#cc99ff',name:'Lexi Definitia',   category:'Vocabulary'},
      {gx:6, gy:12, color:'#ffaa44',name:'Rooter Double-L',   category:'Spelling'},
      {gx:24, gy:11, color:'#44ffcc',name:'Colin Apostrophe',   category:'Punctuation'},
      {gx:1, gy:8, color:'#cc3333',name:'Thane Narrator',   category:'Reading Comprehension'},
      {gx:18, gy:13, color:'#ff6699',name:'Dash Exclama',   category:'Punctuation'},
      {gx:2, gy:9, color:'#4488dd',name:'Vera Predicate',   category:'Grammar'},
      {gx:3, gy:6, color:'#ddaa55',name:'Sue Syllabicus',   category:'Spelling'},
    ]},

  { name:'Idiom Isles',    skin:'isles', bg:'#eafbf9',t1:'#c7f0e8',t2:'#aee6da',wall:'#2fa393',exit:'#FFD23F',
    npcs:[
      {gx:11, gy:8, color:'#44ccff',name:'Silas Letterly',   category:'Spelling'},
      {gx:11, gy:7, color:'#5599ee',name:'Vera Modifi',   category:'Grammar'},
      {gx:7, gy:10, color:'#aa66ff',name:'Rhyma Lexicon',   category:'Vocabulary'},
      {gx:12, gy:3, color:'#bb77ee',name:'Wanda Vocabelle',   category:'Vocabulary'},
      {gx:17, gy:6, color:'#aa66ff',name:'Rufus Thesauris',   category:'Vocabulary'},
      {gx:9, gy:13, color:'#bb77ee',name:'Nuance Contextra',   category:'Vocabulary'},
      {gx:15, gy:12, color:'#ffcc88',name:'Verbo Thesauris',   category:'Vocabulary'},
      {gx:10, gy:8, color:'#ffcc44',name:'Brack Semicolonia',   category:'Punctuation'},
      {gx:6, gy:1, color:'#66aaff',name:'Petra Verbington',   category:'Grammar'},
      {gx:7, gy:9, color:'#ffcc88',name:'Lexi Contextra',   category:'Vocabulary'},
      {gx:12, gy:6, color:'#cc88ff',name:'Prefixia Vocabelle',   category:'Vocabulary'},
      {gx:7, gy:8, color:'#ff7777',name:'Rook Plotford',   category:'Reading Comprehension'},
      {gx:5, gy:10, color:'#44ccff',name:'Sue Silentson',   category:'Spelling'},
      {gx:13, gy:3, color:'#cc3333',name:'Sumara Storywell',   category:'Reading Comprehension'},
      {gx:19, gy:5, color:'#ffcc44',name:'Quill Bracketine',   category:'Punctuation'},
      {gx:21, gy:12, color:'#cc99ff',name:'Suffix Lexicon',   category:'Vocabulary'},
      {gx:20, gy:12, color:'#9955dd',name:'Sy Wordsmith',   category:'Vocabulary'},
    ]},

  { name:'Inference Inlet',    skin:'inlet', bg:'#eef3f5',t1:'#d3e2e7',t2:'#c1d5db',wall:'#5a7d87',exit:'#3EC6E0',
    npcs:[
      {gx:18, gy:8, color:'#ff9999',name:'Detail Storywell',   category:'Reading Comprehension'},
      {gx:20, gy:3, color:'#ff7777',name:'Rhea Detailson',   category:'Reading Comprehension'},
      {gx:10, gy:8, color:'#cc3333',name:'Elenora Inferson',   category:'Reading Comprehension'},
      {gx:9, gy:3, color:'#66aaff',name:'Petra Verbington',   category:'Grammar'},
      {gx:5, gy:13, color:'#5599ee',name:'Dahlia Syntaxia',   category:'Grammar'},
      {gx:2, gy:2, color:'#ff4444',name:'Endra Analytika',   category:'Reading Comprehension'},
      {gx:16, gy:5, color:'#bb77ee',name:'Wanda Definitia',   category:'Vocabulary'},
      {gx:5, gy:8, color:'#cc99ff',name:'Thesa Thesauris',   category:'Vocabulary'},
      {gx:10, gy:6, color:'#dd6666',name:'Narro Themeston',   category:'Reading Comprehension'},
      {gx:24, gy:12, color:'#ffaa44',name:'Dave Diction',   category:'Spelling'},
      {gx:17, gy:2, color:'#4488dd',name:'Roland Subjectine',   category:'Grammar'},
      {gx:13, gy:3, color:'#ff9999',name:'Foresha Chapterly',   category:'Reading Comprehension'},
      {gx:14, gy:4, color:'#ff4444',name:'Chronicle Reads',   category:'Reading Comprehension'},
      {gx:6, gy:13, color:'#ff9999',name:'Cole Contextine',   category:'Reading Comprehension'},
      {gx:8, gy:12, color:'#ff7777',name:'Themis Reads',   category:'Reading Comprehension'},
      {gx:7, gy:9, color:'#ffcc44',name:'Brack Dashford',   category:'Punctuation'},
      {gx:16, gy:9, color:'#bb88ff',name:'Sue Wordwright',   category:'Spelling'},
      {gx:21, gy:10, color:'#ffaa88',name:'Sal Quotewright',   category:'Punctuation'},
    ]},

  { name:'Pronoun Peaks',    skin:'peaks', bg:'#eef6fc',t1:'#d7ecf8',t2:'#c7e3f5',wall:'#6a8fb8',exit:'#3EC6E0',
    npcs:[
      {gx:21, gy:8, color:'#5599ee',name:'Dahlia Syntaxia',   category:'Grammar'},
      {gx:24, gy:7, color:'#88ccaa',name:'Roland Grammarian',   category:'Grammar'},
      {gx:20, gy:12, color:'#66aaff',name:'Marla Syntaxia',   category:'Grammar'},
      {gx:14, gy:7, color:'#ff9999',name:'Detail Plotford',   category:'Reading Comprehension'},
      {gx:19, gy:12, color:'#66aaff',name:'Tobias Clausewell',   category:'Grammar'},
      {gx:15, gy:10, color:'#bb77ee',name:'Prefixia Wordsmith',   category:'Vocabulary'},
      {gx:18, gy:5, color:'#44ffcc',name:'Quill Colonade',   category:'Punctuation'},
      {gx:14, gy:8, color:'#88ccaa',name:'Corvin Clausewell',   category:'Grammar'},
      {gx:23, gy:12, color:'#4488dd',name:'Gus Predicate',   category:'Grammar'},
      {gx:13, gy:11, color:'#99ff99',name:'Petra Verbington',   category:'Grammar'},
      {gx:15, gy:2, color:'#99ff99',name:'Ines Subjectine',   category:'Grammar'},
      {gx:2, gy:8, color:'#ff66cc',name:'Sue Alphabette',   category:'Spelling'},
      {gx:2, gy:2, color:'#88ddff',name:'Quinn Bracketine',   category:'Punctuation'},
      {gx:12, gy:9, color:'#4488dd',name:'Odette Pronounce',   category:'Grammar'},
      {gx:3, gy:5, color:'#ffaa88',name:'Dash Exclama',   category:'Punctuation'},
      {gx:8, gy:11, color:'#4488dd',name:'Nadia Clausewell',   category:'Grammar'},
      {gx:20, gy:5, color:'#ff8888',name:'Dot Wordwright',   category:'Spelling'},
      {gx:19, gy:6, color:'#9955dd',name:'Suffix Thesauris',   category:'Vocabulary'},
      {gx:3, gy:12, color:'#ee8888',name:'Cole Analytika',   category:'Reading Comprehension'},
    ]},

  { name:'Semicolon Sanctuary',    skin:'sanctuary', bg:'#f0f7ee',t1:'#d9ecd1',t2:'#c9e3be',wall:'#6a9a52',exit:'#4CD964',
    npcs:[
      {gx:6, gy:5, color:'#ffdd77',name:'Ellie Dashford',   category:'Punctuation'},
      {gx:11, gy:10, color:'#44ffcc',name:'Sal Dashford',   category:'Punctuation'},
      {gx:14, gy:3, color:'#ffdd77',name:'Dash Apostrophe',   category:'Punctuation'},
      {gx:4, gy:13, color:'#bb88ff',name:'Benny Rooter',   category:'Spelling'},
      {gx:5, gy:9, color:'#5599ee',name:'Tobias Subjectine',   category:'Grammar'},
      {gx:8, gy:13, color:'#cc88ff',name:'Colette Nonym',   category:'Vocabulary'},
      {gx:12, gy:4, color:'#ffaa88',name:'Brack Quotewright',   category:'Punctuation'},
      {gx:18, gy:11, color:'#77bbff',name:'Marcus Adjectivo',   category:'Grammar'},
      {gx:23, gy:12, color:'#ffcc44',name:'Annie Ellipsius',   category:'Punctuation'},
      {gx:23, gy:10, color:'#ffaa88',name:'Perry Parenthesi',   category:'Punctuation'},
      {gx:17, gy:11, color:'#ff66cc',name:'Vowella Vowelson',   category:'Spelling'},
      {gx:11, gy:3, color:'#88ccaa',name:'Vera Pronounce',   category:'Grammar'},
      {gx:17, gy:1, color:'#9955dd',name:'Sy Idiomatic',   category:'Vocabulary'},
      {gx:17, gy:3, color:'#bb88ff',name:'Alva Letterly',   category:'Spelling'},
      {gx:24, gy:7, color:'#ffdd77',name:'Colin Quotewright',   category:'Punctuation'},
      {gx:7, gy:9, color:'#ff6699',name:'Semi Quotewright',   category:'Punctuation'},
      {gx:5, gy:1, color:'#ff6699',name:'Quill Periodson',   category:'Punctuation'},
      {gx:7, gy:2, color:'#ffdd77',name:'Wyn Parenthesi',   category:'Punctuation'},
      {gx:22, gy:6, color:'#ff9999',name:'Endra Summariza',   category:'Reading Comprehension'},
      {gx:11, gy:5, color:'#ff9999',name:'Themis Summariza',   category:'Reading Comprehension'},
    ]},

  { name:'Etymology Estate',    skin:'estate', bg:'#f9f0e6',t1:'#e8d2b0',t2:'#dcc097',wall:'#7a5638',exit:'#FF9F45',
    npcs:[
      {gx:9, gy:11, color:'#cc88ff',name:'Nuance Synonyma',   category:'Vocabulary'},
      {gx:5, gy:10, color:'#99ff99',name:'Vera Articleton',   category:'Grammar'},
      {gx:22, gy:9, color:'#9955dd',name:'Metta Contextra',   category:'Vocabulary'},
      {gx:14, gy:5, color:'#ff66cc',name:'Alva Syllabicus',   category:'Spelling'},
      {gx:2, gy:6, color:'#ff6699',name:'Dash Quotewright',   category:'Punctuation'},
      {gx:11, gy:10, color:'#cc88ff',name:'Rhyma Nonym',   category:'Vocabulary'},
      {gx:4, gy:2, color:'#ee8888',name:'Plotwell Passagewick',   category:'Reading Comprehension'},
      {gx:8, gy:12, color:'#ffcc88',name:'Sy Idiomatic',   category:'Vocabulary'},
      {gx:15, gy:2, color:'#cc88ff',name:'Zin Lexicon',   category:'Vocabulary'},
      {gx:20, gy:13, color:'#9955dd',name:'Verbo Synonyma',   category:'Vocabulary'},
      {gx:4, gy:6, color:'#ff66cc',name:'Benny Double-L',   category:'Spelling'},
      {gx:15, gy:7, color:'#cc88ff',name:'Colette Wordsmith',   category:'Vocabulary'},
      {gx:5, gy:8, color:'#ffcc44',name:'Hy Bracketine',   category:'Punctuation'},
      {gx:16, gy:12, color:'#5599ee',name:'Cyrus Syntaxia',   category:'Grammar'},
      {gx:5, gy:5, color:'#cc88ff',name:'Lexi Wordsmith',   category:'Vocabulary'},
      {gx:13, gy:13, color:'#cc99ff',name:'Wanda Idiomatic',   category:'Vocabulary'},
      {gx:6, gy:6, color:'#ee8888',name:'Narro Themeston',   category:'Reading Comprehension'},
      {gx:15, gy:11, color:'#44ffcc',name:'Quinn Quotewright',   category:'Punctuation'},
      {gx:2, gy:8, color:'#88ccaa',name:'Roland Modifi',   category:'Grammar'},
      {gx:8, gy:2, color:'#aa66ff',name:'Thesa Definitia',   category:'Vocabulary'},
      {gx:6, gy:1, color:'#aa66ff',name:'Anton Nonym',   category:'Vocabulary'},
    ]},

  { name:'Context Clues Cavern',    skin:'cavern', bg:'#f1eefb',t1:'#dcd3f2',t2:'#cabfe9',wall:'#6a4fae',exit:'#7C5CFF',
    npcs:[
      {gx:23, gy:10, color:'#cc3333',name:'Detail Passagewick',   category:'Reading Comprehension'},
      {gx:13, gy:4, color:'#5599ee',name:'Alden Grammarian',   category:'Grammar'},
      {gx:23, gy:13, color:'#aa66ff',name:'Zin Antonym',   category:'Vocabulary'},
      {gx:20, gy:2, color:'#cc3333',name:'Sumara Contextine',   category:'Reading Comprehension'},
      {gx:17, gy:3, color:'#5599ee',name:'Petra Clausewell',   category:'Grammar'},
      {gx:16, gy:10, color:'#44ccff',name:'Lettie Rooter',   category:'Spelling'},
      {gx:13, gy:13, color:'#cc3333',name:'Contexta Storywell',   category:'Reading Comprehension'},
      {gx:19, gy:4, color:'#ffaa88',name:'Quinn Hyphenwell',   category:'Punctuation'},
      {gx:23, gy:9, color:'#ee8888',name:'Rook Narrator',   category:'Reading Comprehension'},
      {gx:3, gy:7, color:'#88ccaa',name:'Odette Tenseford',   category:'Grammar'},
      {gx:12, gy:7, color:'#ff7777',name:'Themis Reads',   category:'Reading Comprehension'},
      {gx:21, gy:9, color:'#aa66ff',name:'Suffix Nonym',   category:'Vocabulary'},
      {gx:6, gy:10, color:'#ff7777',name:'Rhea Storywell',   category:'Reading Comprehension'},
      {gx:10, gy:11, color:'#cc3333',name:'Elenora Inferson',   category:'Reading Comprehension'},
      {gx:2, gy:7, color:'#ff8888',name:'Consie Letterly',   category:'Spelling'},
      {gx:6, gy:9, color:'#ff4444',name:'Foresha Contextine',   category:'Reading Comprehension'},
      {gx:23, gy:7, color:'#ff7777',name:'Cole Reads',   category:'Reading Comprehension'},
      {gx:4, gy:10, color:'#ff4444',name:'Endra Narrator',   category:'Reading Comprehension'},
      {gx:19, gy:13, color:'#44ffcc',name:'Ollie Colonade',   category:'Punctuation'},
      {gx:19, gy:12, color:'#ff66cc',name:'Sam Diction',   category:'Spelling'},
      {gx:10, gy:7, color:'#ff9999',name:'Inferra Summariza',   category:'Reading Comprehension'},
      {gx:13, gy:7, color:'#ff6699',name:'Annie Ellipsius',   category:'Punctuation'},
    ]},

  { name:'The Grand Grammarium',    skin:'grammarium', bg:'#fdf8ea',t1:'#f5e7bd',t2:'#eeda9c',wall:'#c9a53a',exit:'#FFD23F',
    npcs:[
      {gx:22, gy:11, color:'#9955dd',name:'Sy Thesauris',   category:'Vocabulary'},
      {gx:1, gy:12, color:'#4488dd',name:'Tobias Predicate',   category:'Grammar'},
      {gx:11, gy:1, color:'#bb88ff',name:'Rooter Vowelson',   category:'Spelling'},
      {gx:8, gy:7, color:'#ffaa44',name:'Vowella Spellman',   category:'Spelling'},
      {gx:14, gy:11, color:'#ff8888',name:'Sue Mnemonic',   category:'Spelling'},
      {gx:15, gy:11, color:'#5599ee',name:'Marcus Nounsworth',   category:'Grammar'},
      {gx:10, gy:5, color:'#99ff99',name:'Fenwick Articleton',   category:'Grammar'},
      {gx:23, gy:4, color:'#4488dd',name:'Nadia Clausewell',   category:'Grammar'},
      {gx:13, gy:11, color:'#88ccaa',name:'Gus Adjectivo',   category:'Grammar'},
      {gx:18, gy:11, color:'#ffcc44',name:'Semi Periodson',   category:'Punctuation'},
      {gx:8, gy:5, color:'#ff7777',name:'Rhea Reads',   category:'Reading Comprehension'},
      {gx:23, gy:9, color:'#77bbff',name:'Roland Verbington',   category:'Grammar'},
      {gx:9, gy:5, color:'#ffcc88',name:'Zin Etymon',   category:'Vocabulary'},
      {gx:18, gy:13, color:'#5599ee',name:'Vera Nounsworth',   category:'Grammar'},
      {gx:10, gy:9, color:'#88ccaa',name:'Ines Modifi',   category:'Grammar'},
      {gx:14, gy:3, color:'#88ddff',name:'Carl Exclama',   category:'Punctuation'},
      {gx:16, gy:11, color:'#77bbff',name:'Odette Articleton',   category:'Grammar'},
      {gx:3, gy:6, color:'#5599ee',name:'Alden Clausewell',   category:'Grammar'},
      {gx:7, gy:6, color:'#aa66ff',name:'Suffix Contextra',   category:'Vocabulary'},
      {gx:5, gy:13, color:'#88ccaa',name:'Petra Verbington',   category:'Grammar'},
      {gx:6, gy:3, color:'#77bbff',name:'Cyrus Syntaxia',   category:'Grammar'},
      {gx:24, gy:7, color:'#dd6666',name:'Sumara Chapterly',   category:'Reading Comprehension'},
      {gx:18, gy:5, color:'#ff6699',name:'Sal Ellipsius',   category:'Punctuation'},
    ]},
];

const WALLS=[
  [1,1],[2,1],[3,1],[4,1],[8,1],[9,1],[10,1],[14,1],[15,1],[16,1],[20,1],[21,1],
  [1,2],[21,2],[1,3],[21,3],[1,4],[21,4],[1,5],[21,5],
  [4,4],[5,4],[6,4],[16,4],[17,4],[18,4],
  [4,7],[5,7],[6,7],[16,7],[17,7],[18,7],
  [8,6],[9,6],[13,6],[14,6],
  [3,9],[4,9],[8,9],[9,9],[13,9],[14,9],[18,9],[19,9],
  [1,11],[2,11],[20,11],[21,11]
];
